name: Build and Publish

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    uses: mikopbx/.github-workflows/.github/workflows/extension-publish.yml@master
    with:
      initial_version: "1.218"
    secrets: inherit